{
 "title": "App Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "App replicas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"app\"}",
     "legendFormat": "replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=\"app\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"app\"}[$__rate_interval]))",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "HTTP requests throughput (/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_request_size_count{ingress=\"app\"}[$__rate_interval])",
     "legendFormat": "request/s"
    },
    {
     "expr": "rate(nginx_ingress_controller_request_size_count{ingress=\"app\", status=~\"2.*\"}[$__rate_interval])",
     "legendFormat": "2xx/s"
    },
    {
     "expr": "rate(nginx_ingress_controller_request_size_count{ingress=\"app\", status=~\"5.*\"}[$__rate_interval])",
     "legendFormat": "5xx/s"
    }
   ]
  }
 ]
}